### PR TITLE
Feature/ct 3 basic search api call

### PR DESCRIPTION
**Pull request by bapower**

### CODE REVIEW

**Review by elarens — APPROVED** [review]
My only concern is with naming of components but it's a really a minor issue. I'll fix it after the branch is merged.

**Review by swt144 — APPROVED** [review]
I'll need to brush up more on react to contribute better, but from what I could tell, the changes made sense and seemed to correct prior issues (for example, the Country drop down had onGenderChange updated to be onCountryChange)

**Review by bragu — COMMENTED** [review]
You can remove the file frontend/package-lock.json from git add and git commit... It is not required.

**Comment by bragu** [comment]
I see the message "This branch is out-of-date with base branch. Did you first pull the latest from main? Below are the instructions from Git guide.

Steps to rebasing or merging:
Make sure your local version of the main branch is up to date: git checkout main && git pull
Checkout your branch: git checkout <your-branch-name>
To merge: git merge main

**Pull request merged**
