### PR TITLE
Feature/ct 28 parse and display search results

### PR DESCRIPTION
**Pull request by bapower**

### CODE REVIEW

**Review by elarens — CHANGES_REQUESTED** [review]
The column structure that the table was displaying was based on the columns that clinical analysts (well, Barbara) pre-select for trials view. It's the most convenient default setup for them. My suggestion is to keep the columns but populate the content with real data where it's available and use placeholders for the missing data.

**Review by bragu — APPROVED** [review]
I assume the const data = [..] will be removed later once the parsed results are displayed.

**Comment by bapower** [comment]
> I assume the const data = [..] will be removed later once the parsed results are displayed.

No, this _is_ the PR to display parsed results and that is part of passing them to the view and parsing them.

**Comment by bapower** [comment]
> The column structure that the table was displaying was based on the columns that clinical analysts (well, Barbara) pre-select for trials view. It's the most convenient default setup for them. My suggestion is to keep the columns but populate the content with real data where it's available and use placeholders for the missing data.

This is the data that is returned from the API, if it is the wrong data we should take it up with @bragu, not display dummy data.

**Comment by elarens** [comment]
> > The column structure that the table was displaying was based on the columns that clinical analysts (well, Barbara) pre-select for trials view. It's the most convenient default setup for them. My suggestion is to keep the columns but populate the content with real data where it's available and use placeholders for the missing data.
> 
> This is the data that is returned from the API, if it is the wrong data we should take it up with @bragu, not display dummy data.

Having all the columns in the table will allow me to make certain design decisions about. Without them, I cannot do it. They are important. I don't understand why having dummy data in the table bothers you. Is it hard from the implementation viewpoint? Please help me understand. We'll substitute dummy data with real data as soon as they are available.

**Review by elarens — APPROVED** [review]
I'll work on other elements while waiting for Balaji's API expansion, so the ListViewTable shouldn't affect me in the meantime :-)

**Pull request merged**
